/*
 * Cisco Intersight
 *
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-04-17T15:33:06-07:00.
 *
 * API version: 1.0.9-1628
 * Contact: intersight@cisco.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/* Customised for isctl */
package openapi

import (
	"encoding/json"
)

// FirmwareEula EULA (End User License Agreement) acceptance status for an account to use cisco.com, to download software.
type FirmwareEula struct {
	MoBaseMo `yaml:"MoBaseMo,inline"`
	// EULA acceptance status for the account.
	Accepted *bool `json:"Accepted,omitempty" yaml:"Accepted,omitempty"`
	// EULA acceptance form content provided by cisco.com.
	Content *string                 `json:"Content,omitempty" yaml:"Content,omitempty"`
	Account *IamAccountRelationship `json:"Account,omitempty" yaml:"Account,omitempty"`
}

// NewFirmwareEula instantiates a new FirmwareEula object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirmwareEula() *FirmwareEula {
	this := FirmwareEula{}
	return &this
}

// NewFirmwareEulaWithDefaults instantiates a new FirmwareEula object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirmwareEulaWithDefaults() *FirmwareEula {
	this := FirmwareEula{}
	return &this
}

// GetAccepted returns the Accepted field value if set, zero value otherwise.
func (o *FirmwareEula) GetAccepted() bool {
	if o == nil || o.Accepted == nil {
		var ret bool
		return ret
	}
	return *o.Accepted
}

// GetAcceptedOk returns a tuple with the Accepted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirmwareEula) GetAcceptedOk() (*bool, bool) {
	if o == nil || o.Accepted == nil {
		return nil, false
	}
	return o.Accepted, true
}

// HasAccepted returns a boolean if a field has been set.
func (o *FirmwareEula) HasAccepted() bool {
	if o != nil && o.Accepted != nil {
		return true
	}

	return false
}

// SetAccepted gets a reference to the given bool and assigns it to the Accepted field.
func (o *FirmwareEula) SetAccepted(v bool) {
	o.Accepted = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *FirmwareEula) GetContent() string {
	if o == nil || o.Content == nil {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirmwareEula) GetContentOk() (*string, bool) {
	if o == nil || o.Content == nil {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *FirmwareEula) HasContent() bool {
	if o != nil && o.Content != nil {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *FirmwareEula) SetContent(v string) {
	o.Content = &v
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *FirmwareEula) GetAccount() IamAccountRelationship {
	if o == nil || o.Account == nil {
		var ret IamAccountRelationship
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirmwareEula) GetAccountOk() (*IamAccountRelationship, bool) {
	if o == nil || o.Account == nil {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *FirmwareEula) HasAccount() bool {
	if o != nil && o.Account != nil {
		return true
	}

	return false
}

// SetAccount gets a reference to the given IamAccountRelationship and assigns it to the Account field.
func (o *FirmwareEula) SetAccount(v IamAccountRelationship) {
	o.Account = &v
}

func (o FirmwareEula) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedMoBaseMo, errMoBaseMo := json.Marshal(o.MoBaseMo)
	if errMoBaseMo != nil {
		return []byte{}, errMoBaseMo
	}
	errMoBaseMo = json.Unmarshal([]byte(serializedMoBaseMo), &toSerialize)
	if errMoBaseMo != nil {
		return []byte{}, errMoBaseMo
	}
	if o.Accepted != nil {
		toSerialize["Accepted"] = o.Accepted
	}
	if o.Content != nil {
		toSerialize["Content"] = o.Content
	}
	if o.Account != nil {
		toSerialize["Account"] = o.Account
	}
	return json.Marshal(toSerialize)
}

type NullableFirmwareEula struct {
	value *FirmwareEula
	isSet bool
}

func (v NullableFirmwareEula) Get() *FirmwareEula {
	return v.value
}

func (v *NullableFirmwareEula) Set(val *FirmwareEula) {
	v.value = val
	v.isSet = true
}

func (v NullableFirmwareEula) IsSet() bool {
	return v.isSet
}

func (v *NullableFirmwareEula) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirmwareEula(val *FirmwareEula) *NullableFirmwareEula {
	return &NullableFirmwareEula{value: val, isSet: true}
}

func (v NullableFirmwareEula) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirmwareEula) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
