/*
 * Cisco Intersight
 *
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-04-17T15:33:06-07:00.
 *
 * API version: 1.0.9-1628
 * Contact: intersight@cisco.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/* Customised for isctl */
package openapi

import (
	"encoding/json"
)

// VirtualizationHost Common attributes of any host associated to a hypervisor manager. Serves as a base class for all concrete host types A Host belongs to a datacenter and optionally to a cluster, and runs virtual machines on it. A host is basically a hardware platform that runs the VMs. Depending on the capacity of the host, it can support 100s of virtual machines.
type VirtualizationHost struct {
	VirtualizationSourceDevice `yaml:"VirtualizationSourceDevice,inline"`
	CpuInfo                    *VirtualizationCpuInfo `json:"CpuInfo,omitempty" yaml:"CpuInfo,omitempty"`
	HardwareInfo               *InfraHardwareInfo     `json:"HardwareInfo,omitempty" yaml:"HardwareInfo,omitempty"`
	// Identifies the broad type of the underlying hypervisor.
	HypervisorType *string `json:"HypervisorType,omitempty" yaml:"HypervisorType,omitempty"`
	// The internally generated identity of this host. This entity is not manipulated by users. It aids in uniquely identifying the datacenter object. For VMware, this is an MOR (managed object reference).
	Identity *string `json:"Identity,omitempty" yaml:"Identity,omitempty"`
	// Is this host in maintenance mode. Set to true or false.
	MaintenanceMode *bool                         `json:"MaintenanceMode,omitempty" yaml:"MaintenanceMode,omitempty"`
	MemoryCapacity  *VirtualizationMemoryCapacity `json:"MemoryCapacity,omitempty" yaml:"MemoryCapacity,omitempty"`
	// Commercial model information about this hardware.
	Model *string `json:"Model,omitempty" yaml:"Model,omitempty"`
	// Name of this host supplied by user. It is not the identity of the host. The name is subject to user manipulations.
	Name              *string                        `json:"Name,omitempty" yaml:"Name,omitempty"`
	ProcessorCapacity *VirtualizationComputeCapacity `json:"ProcessorCapacity,omitempty" yaml:"ProcessorCapacity,omitempty"`
	ProductInfo       *VirtualizationProductInfo     `json:"ProductInfo,omitempty" yaml:"ProductInfo,omitempty"`
	// Serial number of this host (internally generated).
	Serial *string `json:"Serial,omitempty" yaml:"Serial,omitempty"`
	// Host health status, as reported by the hypervisor platform.
	Status *string `json:"Status,omitempty" yaml:"Status,omitempty"`
	// The uptime of the host, stored as Duration (from w3c).
	UpTime *string `json:"UpTime,omitempty" yaml:"UpTime,omitempty"`
	// Universally unique identity of this host (example b3d4483b-5560-9342-8309-b486c9236610). Internally generated.
	Uuid *string `json:"Uuid,omitempty" yaml:"Uuid,omitempty"`
	// Commercial vendor details of this hardware.
	Vendor *string `json:"Vendor,omitempty" yaml:"Vendor,omitempty"`
}

// NewVirtualizationHost instantiates a new VirtualizationHost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVirtualizationHost() *VirtualizationHost {
	this := VirtualizationHost{}
	var hypervisorType string = "Unknown"
	this.HypervisorType = &hypervisorType
	var status string = "Unknown"
	this.Status = &status
	return &this
}

// NewVirtualizationHostWithDefaults instantiates a new VirtualizationHost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVirtualizationHostWithDefaults() *VirtualizationHost {
	this := VirtualizationHost{}
	var hypervisorType string = "Unknown"
	this.HypervisorType = &hypervisorType
	var status string = "Unknown"
	this.Status = &status
	return &this
}

// GetCpuInfo returns the CpuInfo field value if set, zero value otherwise.
func (o *VirtualizationHost) GetCpuInfo() VirtualizationCpuInfo {
	if o == nil || o.CpuInfo == nil {
		var ret VirtualizationCpuInfo
		return ret
	}
	return *o.CpuInfo
}

// GetCpuInfoOk returns a tuple with the CpuInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationHost) GetCpuInfoOk() (*VirtualizationCpuInfo, bool) {
	if o == nil || o.CpuInfo == nil {
		return nil, false
	}
	return o.CpuInfo, true
}

// HasCpuInfo returns a boolean if a field has been set.
func (o *VirtualizationHost) HasCpuInfo() bool {
	if o != nil && o.CpuInfo != nil {
		return true
	}

	return false
}

// SetCpuInfo gets a reference to the given VirtualizationCpuInfo and assigns it to the CpuInfo field.
func (o *VirtualizationHost) SetCpuInfo(v VirtualizationCpuInfo) {
	o.CpuInfo = &v
}

// GetHardwareInfo returns the HardwareInfo field value if set, zero value otherwise.
func (o *VirtualizationHost) GetHardwareInfo() InfraHardwareInfo {
	if o == nil || o.HardwareInfo == nil {
		var ret InfraHardwareInfo
		return ret
	}
	return *o.HardwareInfo
}

// GetHardwareInfoOk returns a tuple with the HardwareInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationHost) GetHardwareInfoOk() (*InfraHardwareInfo, bool) {
	if o == nil || o.HardwareInfo == nil {
		return nil, false
	}
	return o.HardwareInfo, true
}

// HasHardwareInfo returns a boolean if a field has been set.
func (o *VirtualizationHost) HasHardwareInfo() bool {
	if o != nil && o.HardwareInfo != nil {
		return true
	}

	return false
}

// SetHardwareInfo gets a reference to the given InfraHardwareInfo and assigns it to the HardwareInfo field.
func (o *VirtualizationHost) SetHardwareInfo(v InfraHardwareInfo) {
	o.HardwareInfo = &v
}

// GetHypervisorType returns the HypervisorType field value if set, zero value otherwise.
func (o *VirtualizationHost) GetHypervisorType() string {
	if o == nil || o.HypervisorType == nil {
		var ret string
		return ret
	}
	return *o.HypervisorType
}

// GetHypervisorTypeOk returns a tuple with the HypervisorType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationHost) GetHypervisorTypeOk() (*string, bool) {
	if o == nil || o.HypervisorType == nil {
		return nil, false
	}
	return o.HypervisorType, true
}

// HasHypervisorType returns a boolean if a field has been set.
func (o *VirtualizationHost) HasHypervisorType() bool {
	if o != nil && o.HypervisorType != nil {
		return true
	}

	return false
}

// SetHypervisorType gets a reference to the given string and assigns it to the HypervisorType field.
func (o *VirtualizationHost) SetHypervisorType(v string) {
	o.HypervisorType = &v
}

// GetIdentity returns the Identity field value if set, zero value otherwise.
func (o *VirtualizationHost) GetIdentity() string {
	if o == nil || o.Identity == nil {
		var ret string
		return ret
	}
	return *o.Identity
}

// GetIdentityOk returns a tuple with the Identity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationHost) GetIdentityOk() (*string, bool) {
	if o == nil || o.Identity == nil {
		return nil, false
	}
	return o.Identity, true
}

// HasIdentity returns a boolean if a field has been set.
func (o *VirtualizationHost) HasIdentity() bool {
	if o != nil && o.Identity != nil {
		return true
	}

	return false
}

// SetIdentity gets a reference to the given string and assigns it to the Identity field.
func (o *VirtualizationHost) SetIdentity(v string) {
	o.Identity = &v
}

// GetMaintenanceMode returns the MaintenanceMode field value if set, zero value otherwise.
func (o *VirtualizationHost) GetMaintenanceMode() bool {
	if o == nil || o.MaintenanceMode == nil {
		var ret bool
		return ret
	}
	return *o.MaintenanceMode
}

// GetMaintenanceModeOk returns a tuple with the MaintenanceMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationHost) GetMaintenanceModeOk() (*bool, bool) {
	if o == nil || o.MaintenanceMode == nil {
		return nil, false
	}
	return o.MaintenanceMode, true
}

// HasMaintenanceMode returns a boolean if a field has been set.
func (o *VirtualizationHost) HasMaintenanceMode() bool {
	if o != nil && o.MaintenanceMode != nil {
		return true
	}

	return false
}

// SetMaintenanceMode gets a reference to the given bool and assigns it to the MaintenanceMode field.
func (o *VirtualizationHost) SetMaintenanceMode(v bool) {
	o.MaintenanceMode = &v
}

// GetMemoryCapacity returns the MemoryCapacity field value if set, zero value otherwise.
func (o *VirtualizationHost) GetMemoryCapacity() VirtualizationMemoryCapacity {
	if o == nil || o.MemoryCapacity == nil {
		var ret VirtualizationMemoryCapacity
		return ret
	}
	return *o.MemoryCapacity
}

// GetMemoryCapacityOk returns a tuple with the MemoryCapacity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationHost) GetMemoryCapacityOk() (*VirtualizationMemoryCapacity, bool) {
	if o == nil || o.MemoryCapacity == nil {
		return nil, false
	}
	return o.MemoryCapacity, true
}

// HasMemoryCapacity returns a boolean if a field has been set.
func (o *VirtualizationHost) HasMemoryCapacity() bool {
	if o != nil && o.MemoryCapacity != nil {
		return true
	}

	return false
}

// SetMemoryCapacity gets a reference to the given VirtualizationMemoryCapacity and assigns it to the MemoryCapacity field.
func (o *VirtualizationHost) SetMemoryCapacity(v VirtualizationMemoryCapacity) {
	o.MemoryCapacity = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *VirtualizationHost) GetModel() string {
	if o == nil || o.Model == nil {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationHost) GetModelOk() (*string, bool) {
	if o == nil || o.Model == nil {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *VirtualizationHost) HasModel() bool {
	if o != nil && o.Model != nil {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *VirtualizationHost) SetModel(v string) {
	o.Model = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *VirtualizationHost) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationHost) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *VirtualizationHost) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *VirtualizationHost) SetName(v string) {
	o.Name = &v
}

// GetProcessorCapacity returns the ProcessorCapacity field value if set, zero value otherwise.
func (o *VirtualizationHost) GetProcessorCapacity() VirtualizationComputeCapacity {
	if o == nil || o.ProcessorCapacity == nil {
		var ret VirtualizationComputeCapacity
		return ret
	}
	return *o.ProcessorCapacity
}

// GetProcessorCapacityOk returns a tuple with the ProcessorCapacity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationHost) GetProcessorCapacityOk() (*VirtualizationComputeCapacity, bool) {
	if o == nil || o.ProcessorCapacity == nil {
		return nil, false
	}
	return o.ProcessorCapacity, true
}

// HasProcessorCapacity returns a boolean if a field has been set.
func (o *VirtualizationHost) HasProcessorCapacity() bool {
	if o != nil && o.ProcessorCapacity != nil {
		return true
	}

	return false
}

// SetProcessorCapacity gets a reference to the given VirtualizationComputeCapacity and assigns it to the ProcessorCapacity field.
func (o *VirtualizationHost) SetProcessorCapacity(v VirtualizationComputeCapacity) {
	o.ProcessorCapacity = &v
}

// GetProductInfo returns the ProductInfo field value if set, zero value otherwise.
func (o *VirtualizationHost) GetProductInfo() VirtualizationProductInfo {
	if o == nil || o.ProductInfo == nil {
		var ret VirtualizationProductInfo
		return ret
	}
	return *o.ProductInfo
}

// GetProductInfoOk returns a tuple with the ProductInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationHost) GetProductInfoOk() (*VirtualizationProductInfo, bool) {
	if o == nil || o.ProductInfo == nil {
		return nil, false
	}
	return o.ProductInfo, true
}

// HasProductInfo returns a boolean if a field has been set.
func (o *VirtualizationHost) HasProductInfo() bool {
	if o != nil && o.ProductInfo != nil {
		return true
	}

	return false
}

// SetProductInfo gets a reference to the given VirtualizationProductInfo and assigns it to the ProductInfo field.
func (o *VirtualizationHost) SetProductInfo(v VirtualizationProductInfo) {
	o.ProductInfo = &v
}

// GetSerial returns the Serial field value if set, zero value otherwise.
func (o *VirtualizationHost) GetSerial() string {
	if o == nil || o.Serial == nil {
		var ret string
		return ret
	}
	return *o.Serial
}

// GetSerialOk returns a tuple with the Serial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationHost) GetSerialOk() (*string, bool) {
	if o == nil || o.Serial == nil {
		return nil, false
	}
	return o.Serial, true
}

// HasSerial returns a boolean if a field has been set.
func (o *VirtualizationHost) HasSerial() bool {
	if o != nil && o.Serial != nil {
		return true
	}

	return false
}

// SetSerial gets a reference to the given string and assigns it to the Serial field.
func (o *VirtualizationHost) SetSerial(v string) {
	o.Serial = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *VirtualizationHost) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationHost) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *VirtualizationHost) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *VirtualizationHost) SetStatus(v string) {
	o.Status = &v
}

// GetUpTime returns the UpTime field value if set, zero value otherwise.
func (o *VirtualizationHost) GetUpTime() string {
	if o == nil || o.UpTime == nil {
		var ret string
		return ret
	}
	return *o.UpTime
}

// GetUpTimeOk returns a tuple with the UpTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationHost) GetUpTimeOk() (*string, bool) {
	if o == nil || o.UpTime == nil {
		return nil, false
	}
	return o.UpTime, true
}

// HasUpTime returns a boolean if a field has been set.
func (o *VirtualizationHost) HasUpTime() bool {
	if o != nil && o.UpTime != nil {
		return true
	}

	return false
}

// SetUpTime gets a reference to the given string and assigns it to the UpTime field.
func (o *VirtualizationHost) SetUpTime(v string) {
	o.UpTime = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *VirtualizationHost) GetUuid() string {
	if o == nil || o.Uuid == nil {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationHost) GetUuidOk() (*string, bool) {
	if o == nil || o.Uuid == nil {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *VirtualizationHost) HasUuid() bool {
	if o != nil && o.Uuid != nil {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *VirtualizationHost) SetUuid(v string) {
	o.Uuid = &v
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *VirtualizationHost) GetVendor() string {
	if o == nil || o.Vendor == nil {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationHost) GetVendorOk() (*string, bool) {
	if o == nil || o.Vendor == nil {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *VirtualizationHost) HasVendor() bool {
	if o != nil && o.Vendor != nil {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *VirtualizationHost) SetVendor(v string) {
	o.Vendor = &v
}

func (o VirtualizationHost) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedVirtualizationSourceDevice, errVirtualizationSourceDevice := json.Marshal(o.VirtualizationSourceDevice)
	if errVirtualizationSourceDevice != nil {
		return []byte{}, errVirtualizationSourceDevice
	}
	errVirtualizationSourceDevice = json.Unmarshal([]byte(serializedVirtualizationSourceDevice), &toSerialize)
	if errVirtualizationSourceDevice != nil {
		return []byte{}, errVirtualizationSourceDevice
	}
	if o.CpuInfo != nil {
		toSerialize["CpuInfo"] = o.CpuInfo
	}
	if o.HardwareInfo != nil {
		toSerialize["HardwareInfo"] = o.HardwareInfo
	}
	if o.HypervisorType != nil {
		toSerialize["HypervisorType"] = o.HypervisorType
	}
	if o.Identity != nil {
		toSerialize["Identity"] = o.Identity
	}
	if o.MaintenanceMode != nil {
		toSerialize["MaintenanceMode"] = o.MaintenanceMode
	}
	if o.MemoryCapacity != nil {
		toSerialize["MemoryCapacity"] = o.MemoryCapacity
	}
	if o.Model != nil {
		toSerialize["Model"] = o.Model
	}
	if o.Name != nil {
		toSerialize["Name"] = o.Name
	}
	if o.ProcessorCapacity != nil {
		toSerialize["ProcessorCapacity"] = o.ProcessorCapacity
	}
	if o.ProductInfo != nil {
		toSerialize["ProductInfo"] = o.ProductInfo
	}
	if o.Serial != nil {
		toSerialize["Serial"] = o.Serial
	}
	if o.Status != nil {
		toSerialize["Status"] = o.Status
	}
	if o.UpTime != nil {
		toSerialize["UpTime"] = o.UpTime
	}
	if o.Uuid != nil {
		toSerialize["Uuid"] = o.Uuid
	}
	if o.Vendor != nil {
		toSerialize["Vendor"] = o.Vendor
	}
	return json.Marshal(toSerialize)
}

type NullableVirtualizationHost struct {
	value *VirtualizationHost
	isSet bool
}

func (v NullableVirtualizationHost) Get() *VirtualizationHost {
	return v.value
}

func (v *NullableVirtualizationHost) Set(val *VirtualizationHost) {
	v.value = val
	v.isSet = true
}

func (v NullableVirtualizationHost) IsSet() bool {
	return v.isSet
}

func (v *NullableVirtualizationHost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirtualizationHost(val *VirtualizationHost) *NullableVirtualizationHost {
	return &NullableVirtualizationHost{value: val, isSet: true}
}

func (v NullableVirtualizationHost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirtualizationHost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
