/*
 * Cisco Intersight
 *
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-04-17T15:33:06-07:00.
 *
 * API version: 1.0.9-1628
 * Contact: intersight@cisco.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/* Customised for isctl */
package openapi

import (
	"encoding/json"
)

// MetaPropDefinition Definitions for the properties in a meta.
type MetaPropDefinition struct {
	MoBaseComplexType `yaml:"MoBaseComplexType,inline"`
	// API access control for the property. Examples are NoAccess, ReadOnly, CreateOnly etc.
	ApiAccess *string `json:"ApiAccess,omitempty" yaml:"ApiAccess,omitempty"`
	// The name of the property.
	Name *string `json:"Name,omitempty" yaml:"Name,omitempty"`
	// The data-at-rest security protection applied to this property when a Managed Object is persisted. For example, Encrypted or Cleartext.
	OpSecurity *string `json:"OpSecurity,omitempty" yaml:"OpSecurity,omitempty"`
	// Enables the property to be searchable from global search. A value of 0 means this property is not globally searchable.
	SearchWeight *float32 `json:"SearchWeight,omitempty" yaml:"SearchWeight,omitempty"`
}

// NewMetaPropDefinition instantiates a new MetaPropDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaPropDefinition() *MetaPropDefinition {
	this := MetaPropDefinition{}
	var apiAccess string = "NoAccess"
	this.ApiAccess = &apiAccess
	var opSecurity string = "ClearText"
	this.OpSecurity = &opSecurity
	return &this
}

// NewMetaPropDefinitionWithDefaults instantiates a new MetaPropDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaPropDefinitionWithDefaults() *MetaPropDefinition {
	this := MetaPropDefinition{}
	var apiAccess string = "NoAccess"
	this.ApiAccess = &apiAccess
	var opSecurity string = "ClearText"
	this.OpSecurity = &opSecurity
	return &this
}

// GetApiAccess returns the ApiAccess field value if set, zero value otherwise.
func (o *MetaPropDefinition) GetApiAccess() string {
	if o == nil || o.ApiAccess == nil {
		var ret string
		return ret
	}
	return *o.ApiAccess
}

// GetApiAccessOk returns a tuple with the ApiAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaPropDefinition) GetApiAccessOk() (*string, bool) {
	if o == nil || o.ApiAccess == nil {
		return nil, false
	}
	return o.ApiAccess, true
}

// HasApiAccess returns a boolean if a field has been set.
func (o *MetaPropDefinition) HasApiAccess() bool {
	if o != nil && o.ApiAccess != nil {
		return true
	}

	return false
}

// SetApiAccess gets a reference to the given string and assigns it to the ApiAccess field.
func (o *MetaPropDefinition) SetApiAccess(v string) {
	o.ApiAccess = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MetaPropDefinition) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaPropDefinition) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MetaPropDefinition) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MetaPropDefinition) SetName(v string) {
	o.Name = &v
}

// GetOpSecurity returns the OpSecurity field value if set, zero value otherwise.
func (o *MetaPropDefinition) GetOpSecurity() string {
	if o == nil || o.OpSecurity == nil {
		var ret string
		return ret
	}
	return *o.OpSecurity
}

// GetOpSecurityOk returns a tuple with the OpSecurity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaPropDefinition) GetOpSecurityOk() (*string, bool) {
	if o == nil || o.OpSecurity == nil {
		return nil, false
	}
	return o.OpSecurity, true
}

// HasOpSecurity returns a boolean if a field has been set.
func (o *MetaPropDefinition) HasOpSecurity() bool {
	if o != nil && o.OpSecurity != nil {
		return true
	}

	return false
}

// SetOpSecurity gets a reference to the given string and assigns it to the OpSecurity field.
func (o *MetaPropDefinition) SetOpSecurity(v string) {
	o.OpSecurity = &v
}

// GetSearchWeight returns the SearchWeight field value if set, zero value otherwise.
func (o *MetaPropDefinition) GetSearchWeight() float32 {
	if o == nil || o.SearchWeight == nil {
		var ret float32
		return ret
	}
	return *o.SearchWeight
}

// GetSearchWeightOk returns a tuple with the SearchWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaPropDefinition) GetSearchWeightOk() (*float32, bool) {
	if o == nil || o.SearchWeight == nil {
		return nil, false
	}
	return o.SearchWeight, true
}

// HasSearchWeight returns a boolean if a field has been set.
func (o *MetaPropDefinition) HasSearchWeight() bool {
	if o != nil && o.SearchWeight != nil {
		return true
	}

	return false
}

// SetSearchWeight gets a reference to the given float32 and assigns it to the SearchWeight field.
func (o *MetaPropDefinition) SetSearchWeight(v float32) {
	o.SearchWeight = &v
}

func (o MetaPropDefinition) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedMoBaseComplexType, errMoBaseComplexType := json.Marshal(o.MoBaseComplexType)
	if errMoBaseComplexType != nil {
		return []byte{}, errMoBaseComplexType
	}
	errMoBaseComplexType = json.Unmarshal([]byte(serializedMoBaseComplexType), &toSerialize)
	if errMoBaseComplexType != nil {
		return []byte{}, errMoBaseComplexType
	}
	if o.ApiAccess != nil {
		toSerialize["ApiAccess"] = o.ApiAccess
	}
	if o.Name != nil {
		toSerialize["Name"] = o.Name
	}
	if o.OpSecurity != nil {
		toSerialize["OpSecurity"] = o.OpSecurity
	}
	if o.SearchWeight != nil {
		toSerialize["SearchWeight"] = o.SearchWeight
	}
	return json.Marshal(toSerialize)
}

type NullableMetaPropDefinition struct {
	value *MetaPropDefinition
	isSet bool
}

func (v NullableMetaPropDefinition) Get() *MetaPropDefinition {
	return v.value
}

func (v *NullableMetaPropDefinition) Set(val *MetaPropDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaPropDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaPropDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaPropDefinition(val *MetaPropDefinition) *NullableMetaPropDefinition {
	return &NullableMetaPropDefinition{value: val, isSet: true}
}

func (v NullableMetaPropDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaPropDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
